export const FETCH_GIFS = 'FETCH_GIFS';
export const CHANGE_QUERY = 'CHANGE_QUERY';
export const DISPLAY_SPINNER = 'DISPLAY_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
export const END_RESULTS = 'END_RESULTS';

export const FETCH_TRANSLATE_GIF = 'FETCH_TRANSLATE_GIF';

export const POST_FAVORITE = 'POST_FAVORITE';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const OPEN_FAVORITES = 'OPEN_FAVORITES';

export const FETCH_USERID = 'FETCH_USERID';
export const REMOVE_USERID = 'REMOVE_USERID';

export const TOGGLE_LOGIN_MESSAGE = 'TOGGLE_LOGIN_MESSAGE';


export const CHOOSE_SEARCH_TYPE = 'CHOOSE_SEARCH_TYPE';

export const ADJUST_WEIRDNESS = 'ADJUST_WEIRDNESS';