export const FETCH_GIFS = 'FETCH_GIFS';
export const DISPLAY_SPINNER = 'DISPLAY_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const POST_FAVORITE = 'POST_FAVORITE';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const FETCH_USERID = 'FETCH_USERID';