export const POST_FAVORITE_SUCCESS = 'POST_FAVORITE_SUCCESS';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const OPEN_FAVORITES = 'OPEN_FAVORITES';