export const FETCH_GIFS_SUCCESS = 'FETCH_GIFS_SUCCESS';
export const FETCH_GIFS_FAILURE = 'FETCH_GIFS_FAILURE';
export const FETCH_WEIRD_GIF_SUCCESS = 'FETCH_WEIRD_GIF_SUCCESS';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
export const RESET_QUERY = 'RESET_QUERY';
export const TOGGLE_END_RESULTS = 'TOGGLE_END_RESULTS';





