export const CHANGE_QUERY = 'CHANGE_QUERY';
export const FETCH_GIFS_SUCCESS = 'FETCH_GIFS_SUCCESS';
export const END_RESULTS = 'END_RESULTS';
export const FETCH_TRANSLATE_GIF = 'FETCH_TRANSLATE_GIF';
export const FETCH_GIFS_FAILURE = 'FETCH_GIFS_FAILURE';
export const DISPLAY_SPINNER = 'DISPLAY_SPINNER';

