export const TOGGLE_LOGIN_MESSAGE = 'TOGGLE_LOGIN_MESSAGE';
export const ANIMATE_NAVBAR = 'ANIMATE_NAVBAR';
export const FETCH_USERID = 'FETCH_USERID';
export const REMOVE_USERID = 'REMOVE_USERID';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';