export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const TOGGLE_LOGIN_MESSAGE = 'TOGGLE_LOGIN_MESSAGE';
export const ANIMATE_NAVBAR = 'ANIMATE_NAVBAR';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';